// Generated by CoffeeScript 1.7.1
(function() {
  (function() {
    var subNav;
    return subNav = function(owner, props) {
      var ret, ul;
      ({
        defaults: {
          active: '',
          menu: [
            {
              name: '',
              href: ''
            }
          ]
        }
      });
      Dre.extend(defaults, props);
      ret = Dre.component(owner, 'dre-sidebar-subnav');
      ul = ret.ul({
        attr: {
          "class": 'animated fadeIn'
        }
      });
      return Dre.each(defaults.menu, function(val, key) {
        var li;
        if (val.name === defaults.active) {
          li = ul.li({
            attr: {
              "class": 'active'
            }
          });
        } else {
          li = ul.li;
        }
        li.a({
          attr: {
            href: val.href
          }.text(val.name)
        });
      });
    };
  })();

}).call(this);

//# sourceMappingURL=sidebar-subnav.map
