// Generated by CoffeeScript 1.7.1
(function() {
  (function() {
    var Doc, thisGlobal, _ref, _ref1;
    thisGlobal = (_ref = typeof global !== 'undefined' && global) != null ? _ref : {
      global: (_ref1 = typeof window !== 'undefined') != null ? _ref1 : {
        window: this
      }
    };
    Doc = thisGlobal.OJ;
    return thisGlobal.Doc = Doc;
  })();

}).call(this);

//# sourceMappingURL=Doc.map
